############################ Default configuration #########################
baseURL = 'http://rraines.xyz/'
title = 'What is Rob up to?'
# theme
theme = 'ananke'
# disable language
languageCode = 'en-us'
disableLanguages = [""] # desable language from here
resourceDir = "../resources"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

######################### Default Parameters ###########################
[params]
#  text_color = ""
  author = "Rob Raines"
#  favicon = ""
#  site_logo = ""
#  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3
# copyright
copyright = ""
rssLimit = 20
# search *** true or false (if Search is disable Menu will align in Right) ***
search = true

############################## Social Site ##########################
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rraines13"

####################### Banner #######################################