############################ Default configuration #########################
baseURL = 'http://rraines.xyz/'
title = 'What is Rob up to?'
# theme
theme = "stack"
# disable language
languageCode = 'en-us'
disableLanguages = [""] # desable language from here
resourceDir = "../resources"

enableRobotsTXT = true
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

######################### Default Parameters ###########################
[params]
  mainSections = [ "post" ]
  featuredImageField = "image"
  rssFullContent = true
  #  text_color = ""
  author = "Rob Raines"
  #favicon = ""
  #site_logo = ""
  #description = "The last theme you'll ever need. Maybe."
  #choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3
  copyright = ""
  rssLimit = 20
  # search *** true or false (if Search is disable Menu will align in Right) ***
  search = true

[params.footer]
  since = 2023

[params.article]
  math = false
  toc = true
  readingTime = true

[params.article.license]
  enabled = true
  default = "Licensed under CC BY-NC-SA 4.0"

[params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
  emoji = "🍥"
  subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

[params.comments]
  enabled = true
  provider = "disqus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

[params.comments.waline]
    emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

[params.comments.twikoo]

[params.comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

[params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

[params.comments.gitalk]

[params.comments.cusdis]

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/CaiJimmy/hugo-theme-stack"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "twitter"
  name = "Twitter"
  url = "https://twitter.com"

    [menu.social.params]
    icon = "brand-twitter"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = false

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

############################## Social Site ##########################
### [[params.ananke_socials]]
### name = "twitter"
### url = "https://twitter.com/rraines13"

####################### Banner #######################################
